version: '3.9'

services:
  #MongoDS services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #Node API services
  api:
    build: .
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: task-manager-api
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}